Voting logic
datboyakin/everything-news-frontend pull request #3
Opened 2022-04-21 14:44 UTC by datboyakin

Hi there - voting logic is now complete!

2022-04-21 14:48 UTC, jadelandeg commented on src/components/Article.jsx
> +  useEffect(() => {}, [upvote]);
what's happening with this use effect?

2022-04-22 08:34 UTC, jadelandeg commented on src/components/Article.jsx
> +      setUpvote(article.votes + vote);
Here instead of using state as part of the set state call. Should take advantage of the currentVote that setstate takes in its callback. e.g. setUpVote((currVote)=>currVote+vote)

2022-04-22 08:34 UTC, jadelandeg commented on src/components/Article.jsx
> +      setUpvote(article.votes);
same as above here

2022-04-22 08:35 UTC, jadelandeg requested changes
Looking good! Very close,just shouldn't use the state in setState call

2022-04-22 10:18 UTC, corkesw commented on src/components/Article.jsx
> +  const handleLikes = (vote) => {
This could be dryer if we use a Boolean for likeState and flip it in the function. You would need to change some conditions that use it in other parts of the code.

2022-04-22 10:19 UTC, corkesw commented on src/components/Article.jsx
> +      castVote(article_id, vote);
optimistic rendering if fine here but what if the user is offline? We need a catch block to deal with this which should reverse the optimistic rendering and provide some user feedback.

2022-04-22 10:19 UTC, corkesw commented on src/components/Article.jsx
> +      castVote(article_id, vote);
as above

2022-04-23 20:24 UTC, merged